alter table STATLOAD_VAR add constraint FK_STATLOAD_VAR_ON_ID_REPORT foreign key (ID_REPORT) references STATLOAD_REPORT(ID);
alter table STATLOAD_VAR add constraint FK_STATLOAD_VAR_ON_ID_STATPOKAZ foreign key (ID_STATPOKAZ) references STATLOAD_STAT_POKAZ(ID);
alter table STATLOAD_VAR add constraint FK_STATLOAD_VAR_ON_ID_SPRAV foreign key (ID_SPRAV) references STATLOAD_STAT_SPRAV(ID);
create index IDX_STATLOAD_VAR_ON_ID_REPORT on STATLOAD_VAR (ID_REPORT);
create index IDX_STATLOAD_VAR_ON_ID_STATPOKAZ on STATLOAD_VAR (ID_STATPOKAZ);
create index IDX_STATLOAD_VAR_ON_ID_SPRAV on STATLOAD_VAR (ID_SPRAV);
